// CART
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART  = 'REMOVE_PRODUCT_FROM_CART';
export const INCREASE_PRODUCT_IN_CART  = 'INCREASE_PRODUCT_IN_CART';
export const DECREASE_PRODUCT_IN_CART  = 'DECREASE_PRODUCT_IN_CART';
export const CHANGE_COUNT_PRODUCT_IN_CART  = 'CHANGE_COUNT_PRODUCT_IN_CART';
export const UPDATE_TOTAL_PRODUCT_PRICE  = 'UPDATE_TOTAL_PRODUCT_PRICE';
// WISHLIST
export const ADD_PRODUCT_TO_WISHLIST = 'ADD_PRODUCT_TO_WISHLIST';
export const REMOVE_PRODUCT_FROM_WISHLIST = 'REMOVE_PRODUCT_FROM_WISHLIST';